config/routes.rb
Emergency::Application.routes.draw do
  devise_for :users

  root :to => "patients#new"
	resources :patients do
		resources :investigations
		resources :initial_treatments
		resources :complaints
	end

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
	validates :complaint, :presence => true
	belongs_to :patient
	
end

app/models/initial_treatment.rb
class InitialTreatment < ActiveRecord::Base
	validates :treatment, :presence => true
	belongs_to :patient
	
end

app/models/investigation.rb
class Investigation < ActiveRecord::Base
	validates :investigation, :presence => true
	belongs_to :patient
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	validates :first_name, :presence => true
	validates :last_name, :presence => true
	
	has_many :complaints
	has_many :investigations
	has_many :initial_treatments
	
	
	def name
		"#{first_name} #{last_name}"
	end
	
	def gender
		if gender_boolean
			"Female"
			else
				"Male"
			end
	end
	
	def mlc
		if mlc_status
			"MLC case"
		else
			"Non-MLC case"
		end
		
	end
	
	def time
		created_at.in_time_zone("Karachi").strftime("%r %Z")
	end
	
	def date
		created_at.strftime("%d/%m/%Y")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
	before_filter :load_patient
	def create
		@complaint = @patient.complaints.new(params[:complaint])
		if @complaint.save
			respond_to do |format|
				format.html {redirect_to @patient, :notice => 'Complaint Added!'}
				format.js
			end
			
			else
				respond_to do |format|
				format.html {redirect_to @patient, :alert => 'Unable to add complaint!'}
				format.js {render 'fail_create.js.erb'}
			end
		end
	end

	def destroy
		@complaint = @patient.complaints.find(params[:id])
		@complaint.destroy
		respond_to do |format|
			format.html { redirect_to @article, :notice => 'Comment deleted' }
			format.js
		end

	end

private
	def load_patient
		@patient = Patient.find(params[:patient_id])
	end
end

app/controllers/initial_treatments_controller.rb
class InitialTreatmentsController < ApplicationController
	before_filter :load_patient
	def create
		@treatment = @patient.initial_treatments.new(params[:initial_treatment])
		if @treatment.save
			respond_to do |format|
				format.html {redirect_to @patient, :notice => 'Treatment Added!'}
				format.js
			end
			
			else
				respond_to do |format|
				format.html {redirect_to @patient, :alert => 'Unable to add treatment!'}
				format.js {render 'fail_create.js.erb'}
			end
		end
	end

	def destroy
		@treatment = @patient.initial_treatments.find(params[:id])
		@treatment.destroy
		respond_to do |format|
			format.html { redirect_to @article, :notice => 'Comment deleted' }
			format.js
		end
	end

private
	def load_patient
		@patient = Patient.find(params[:patient_id])
	end
end

app/controllers/investigations_controller.rb
class InvestigationsController < ApplicationController
	before_filter :load_patient

	def create
		@investigation = @patient.investigations.new(params[:investigation])
		if @investigation.save
			respond_to do |format|
				format.html {redirect_to @patient, :notice => 'Investigation Added!'}
				format.js
			end
			
			else
				respond_to do |format|
				format.html {redirect_to @patient, :alert => 'Unable to add investigation!'}
				format.js {render 'fail_create.js.erb'}
			end
		end
	end

	def destroy
		@investigation = @patient.investigations.find(params[:id])
		@investigation.destroy
		respond_to do |format|
			format.html { redirect_to @article, :notice => 'Comment deleted' }
			format.js
		end
	end

private
	def load_patient
		@patient = Patient.find(params[:patient_id])
	end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
      format.xml {render xml: @patients}
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/initial_treatments_helper.rb
module InitialTreatmentsHelper
end

app/helpers/investigations_helper.rb
module InvestigationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/complaints/_complaint.html.haml
= div_for complaint do
  %p
    %span.actions
      = link_to 'Delete', patient_complaint_path(:patient_id => @patient, :id => complaint), :confirm => 'Are you sure you want to delete this complaint?', :method => :delete, :remote => true
  = complaint.complaint

app/views/complaints/create.js.erb
$('#complaints').append("<%= escape_javascript(render(@complaint)) %>");
$('#new_complaint')[0].reset();

app/views/complaints/destroy.js.erb
$("#<%= dom_id(@complaint) %>").remove()

app/views/complaints/fail_create.js.erb
alert("<%= @patient.complaint.errors.full_messages.to_sentence %>");

app/views/complaints/new.html.haml
%h3 New Complaint
= form_for [@patient, @patient.complaints.new], :remote => true, :html => {:style => 'display: none;'} do |f|
  .field
    = f.label :complaint
    %br/
    = f.text_field :complaint
  .actions
    = f.submit "Add Complaint"

app/views/complaints/new.js.erb
$("<%= escape_javascript render(:file => 'complaints/new.html.erb') %>").insertAfter('#complaints');
$('#new_complaint').slideDown();
$('#new_complaint_link').hide();

app/views/complaints/show.html.haml
%p#notice= notice
%p
  %b Patient:
  = @complaint.patient.name
%p
  %b Complaint:
  = @complaint.complaint
= link_to 'Edit', edit_complaint_path(@complaint)

app/views/initial_treatments/_initial_treatment.html.haml
= div_for initial_treatment do
  %p
    %span.actions
      = link_to 'Delete', patient_initial_treatment_path(:patient_id => @patient, :id => initial_treatment), :confirm => 'Are you sure?', :method => :delete, :remote => true
  = initial_treatment.treatment

app/views/initial_treatments/create.js.erb
$('#treatments').append("<%= escape_javascript(render(@treatment)) %>");
$('#new_treatment')[0].reset();

app/views/initial_treatments/destroy.js.erb
$("#<%= dom_id(@treatment) %>").remove()

app/views/initial_treatments/fail_create.js.erb
alert("<%= @patient.initial_treatment.errors.full_messages.to_sentence %>");

app/views/initial_treatments/new.html.haml
%h3 New Treatment
= form_for [@patient, @patient.initial_treatments.new], :html => {:style => 'display: none;'} do |f|
  .field
    = f.label :treatment
    %br/
    = f.text_field :treatment
  .actions
    = f.submit 'Add Treatment'

app/views/initial_treatments/new.js.erb
$("<%= escape_javascript render(:file => 'initial_treatments/new.html.erb') %>").insertAfter('#treatments');
$('#new_initial_treatment').slideDown();
$('#new_treatment_link').hide();

app/views/initial_treatments/show.html.haml
%p#notice= notice
%p
  %b Patient:
  = @initial_treatment.patient.name
%p
  %b Treatment:
  = @initial_treatment.treatment
= link_to 'Edit', edit_initial_treatment_path(@initial_treatment)

app/views/investigations/_investigation.html.haml
= div_for investigation do
  %p
    %span.actions
      = link_to 'Delete', patient_investigation_path(:patient_id => @patient, :id => investigation), :confirm => 'Are you sure?', :method => :delete, :remote => true
  = investigation.investigation

app/views/investigations/create.js.erb
$('#investigations').append("<%= escape_javascript(render(@investigation)) %>");
$('#new_investigation')[0].reset();

app/views/investigations/destroy.js.erb
$("#<%= dom_id(@investigation) %>").remove()

app/views/investigations/fail_create.js.erb
alert("<%= @patient.investigation.errors.full_messages.to_sentence %>");

app/views/investigations/new.html.haml
%h3 New Investigation
= form_for [@patient, @patient.investigations.new], :html => {:style => 'display: none;'} do |f|
  .field
    = f.label :investigation
    %br/
    = f.text_field :investigation
  .actions
    = f.submit 'Add Investigation'

app/views/investigations/new.js.erb
$("<%= escape_javascript render(:file => 'investigations/new.html.erb') %>").insertAfter('#investigations');
$('#new_investigation').slideDown();
$('#new_investigation_link').hide();

app/views/investigations/show.html.haml
%p
  %b Patient:
  = @investigation.patient.name
%p
  %b Investigation:
  = @investigation.investigation
= link_to 'Edit', edit_investigation_path(@investigation)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NMC A&E Patient Data Entry System
    = stylesheet_link_tag    "application", :media => :screen
    = stylesheet_link_tag    "print", :media => :print
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = content_tag :p, notice, :class => 'notice' if notice.present?
    = content_tag :p, alert, :class => 'alert' if alert.present?
    = yield
    #footer
      %p This website was designed by banseljaj designs
      %p This website runs on Ruby on Rails

app/views/patients/_form.html.haml
= form_for(@patient) do |f|
  - if @patient.errors.any?
    #error_explanation.noprint
      %h2
        = pluralize(@patient.errors.count, "error")
        prohibited this patient from being saved:
      %ul
        - @patient.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :mlc_status
    %br/
    = f.radio_button :mlc_status, true, :checked => true
    MLC
    \#{f.radio_button :mlc_status, false} Non-MLC
  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name
  .field
    = f.label :last_name
    %br/
    = f.text_field :last_name
  .field
    = f.label :age
    %br/
    = f.text_field :age
  .field
    = f.label :gender
    %br/
    = f.radio_button :gender_boolean, false, :checked => true
    Male
    \#{f.radio_button :gender_boolean, true} Female
  .field
    = f.label :relation
    %br/
    = f.text_field :relation
  .field
    = f.label :address
    %br/
    = f.text_area :address
  .actions
    = f.submit

app/views/patients/_patient.html.haml
= div_for patient do
  #datetime
    %p
      %b Date arrived:
      = @patient.date
    %p
      %b Time arrived:
      = @patient.time
  #MLC
    %p
      %b MLC status:
      = @patient.mlc
  #Biodata
    %p
      %b Patient name:
      = @patient.name
    %p
      %b Age
      = @patient.age
    %p
      %b Gender
      = @patient.gender
    %p
      %b S/O W/O D/O:
      = @patient.relation
    %p
      %b Address:
      = @patient.address
  .noprint
    = link_to 'Edit', edit_patient_path(@patient)
    = link_to 'Back', patients_path

app/views/patients/_sidebar.html.haml
.block.notice.noprint
  %h3 Sidebar
.block.noprint
  %h3 Links
  %ul.navigation
    %li
      %a{:href => new_patient_path} New Patient
    %li
      %a{:href => "#", :onclick => "window.print();return false;"} Print

app/views/patients/edit.html.haml
%h1 Editing patient
= render 'form'
= link_to 'Show', @patient
|
\#{link_to 'Back', patients_path}

app/views/patients/index.html.haml
%h1 Listing patients
%table
  %tr
    %th Date arrived
    %th Time arrived
    %th MLC status
    %th Name
    %th Age
    %th Gender
    %th Relation
    %th Address
    %th
    %th
    %th
  - @patients.each do |patient|
    %tr
      %td= patient.date
      %td= patient.time
      %td= patient.mlc
      %td= patient.name
      %td= patient.age
      %td= patient.gender
      %td= patient.relation
      %td= patient.address
      %td= link_to 'Show', patient
      %td= link_to 'Edit', edit_patient_path(patient)
      %td= link_to 'Destroy', patient, confirm: 'Are you sure?', method: :delete
%br/
= link_to 'New Patient', new_patient_path

app/views/patients/new.html.haml
%h1 New patient
= render 'form'

= link_to 'Back', patients_path

app/views/patients/show.html.haml
#sidebar.noprint
  .right.column
    = render :partial => "sidebar"
= render @patient
#complaints
  %h3 Complaints
  = render @patient.complaints
  .noprint
    = link_to "New Complaint", new_patient_complaint_path(@patient, :format => :js), :remote => true, :id => 'new_complaint_link'
#investigations
  %h3 Investigations
  = render @patient.investigations
  .noprint
    = link_to "New Investigation", new_patient_investigation_path(@patient, :format => :js), :remote => true, :id => 'new_investigation_link'
#treatments
  %h3 Treatments Done
  = render @patient.initial_treatments
  .noprint
    = link_to "New Treatment", new_patient_initial_treatment_path(@patient, :format => :js), :remote => true, :id => 'new_treatment_link'